spring:
  datasource:
    url: jdbc:mysql://localhost:3307/sfg_prod?serverTimezone=UTC
    username: sfg_prod_user
    password: sfg_prod_user
    initialization-mode: always # triggers call of data.sql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    show-sql: false

#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: create_db-spring5-sec18-chap311.sql