spring:
  datasource:
    url: jdbc:mysql://localhost:3307/sfg_dev
    username: sfg_dev_user
    password: sfg_dev_user
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    show-sql: true
  # triggers database initialization with scripts
  sql:
    init:
      mode: always
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: create_db-spring5-sec18-chap311.sql
