spring:
  datasource:
    url: jdbc:mysql://localhost:3307/sfg_dev?serverTimezone=UTC
    username: sfg_dev_user
    password: sfg_dev_user
    initialization-mode: always # triggers call of data.sql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    show-sql: true

#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: src/main/scripts/create_tables-spring5-sec18-chap312.sql