spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_dev?serverTimezone=UTC
    username: sfg_dev_user
    password: sfg_dev_user
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true

    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create_db-spring5-sec18-chap311.sql