spring:
  datasource:
    url: jdbc:mysql://localhost:3307/sfg_dev
    username: sfg_dev_user
    password: sfg_dev_user
  # triggers database initialization with scripts
  # not necessary in our case since no apppropriate
  # data.sql present
  #sql:
  #  init:
  #    mode: always
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    show-sql: true

  #  properties:
  #    javax:
  #      persistence:
  #        schema-generation:
  #          create-source: metadata
  #          scripts:
  #            action: create
  #            create-target: src/main/scripts/create_tables-spring5-sec18-chap311.sql
